// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmFXW3zj-pu4iCPr0jK_PB5YBdc-okf0',
    appId: '1:736751479548:web:518c3d82e9a572755e0579',
    messagingSenderId: '736751479548',
    projectId: 'wolfpack-ec92e',
    authDomain: 'wolfpack-ec92e.firebaseapp.com',
    storageBucket: 'wolfpack-ec92e.firebasestorage.app',
    measurementId: 'G-CPJHGTH8PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2F6B1pRPR7030F_VbSdu9xIPLk3iidFo',
    appId: '1:736751479548:android:2aca2848e71b3c9d5e0579',
    messagingSenderId: '736751479548',
    projectId: 'wolfpack-ec92e',
    storageBucket: 'wolfpack-ec92e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DQ8TussYPMPKsmAHMd3N5Q-84FBnDOI',
    appId: '1:736751479548:ios:dc392ecfe959482e5e0579',
    messagingSenderId: '736751479548',
    projectId: 'wolfpack-ec92e',
    storageBucket: 'wolfpack-ec92e.firebasestorage.app',
    iosBundleId: 'jamil.com.petDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DQ8TussYPMPKsmAHMd3N5Q-84FBnDOI',
    appId: '1:736751479548:ios:dc392ecfe959482e5e0579',
    messagingSenderId: '736751479548',
    projectId: 'wolfpack-ec92e',
    storageBucket: 'wolfpack-ec92e.firebasestorage.app',
    iosBundleId: 'jamil.com.petDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJmFXW3zj-pu4iCPr0jK_PB5YBdc-okf0',
    appId: '1:736751479548:web:823914406208a3bc5e0579',
    messagingSenderId: '736751479548',
    projectId: 'wolfpack-ec92e',
    authDomain: 'wolfpack-ec92e.firebaseapp.com',
    storageBucket: 'wolfpack-ec92e.firebasestorage.app',
    measurementId: 'G-913X6PB070',
  );

}