// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxaEWbPuPG4tZf0bW_-sZeSvVulw8WR8',
    appId: '1:852956645307:web:5f41b3e0338a1c6d2fa69e',
    messagingSenderId: '852956645307',
    projectId: 'sales-e8f5a',
    authDomain: 'sales-e8f5a.firebaseapp.com',
    storageBucket: 'sales-e8f5a.firebasestorage.app',
    measurementId: 'G-BBSBSRFEL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPxRzmBvDSVnyT9RcvCPE87EexrPKXDw',
    appId: '1:852956645307:android:fe883f1ac5d30b832fa69e',
    messagingSenderId: '852956645307',
    projectId: 'sales-e8f5a',
    storageBucket: 'sales-e8f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpLfWJSvr5FZyJJhM90Z8wm1N9wrzq1U',
    appId: '1:852956645307:ios:61fda309388db0f52fa69e',
    messagingSenderId: '852956645307',
    projectId: 'sales-e8f5a',
    storageBucket: 'sales-e8f5a.firebasestorage.app',
    iosBundleId: 'jamil.com.petDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpLfWJSvr5FZyJJhM90Z8wm1N9wrzq1U',
    appId: '1:852956645307:ios:61fda309388db0f52fa69e',
    messagingSenderId: '852956645307',
    projectId: 'sales-e8f5a',
    storageBucket: 'sales-e8f5a.firebasestorage.app',
    iosBundleId: 'jamil.com.petDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoxaEWbPuPG4tZf0bW_-sZeSvVulw8WR8',
    appId: '1:852956645307:web:c63154d001f287b92fa69e',
    messagingSenderId: '852956645307',
    projectId: 'sales-e8f5a',
    authDomain: 'sales-e8f5a.firebaseapp.com',
    storageBucket: 'sales-e8f5a.firebasestorage.app',
    measurementId: 'G-JK05GBDBZS',
  );
}
