import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:get_storage/get_storage.dart';

import 'app/routes/app_pages.dart';
import 'app/uitilies/api/app_constant.dart';
import 'app/uitilies/api/local_storage.dart';
import 'app/uitilies/api/local_storages.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
FlutterLocalNotificationsPlugin();

// Background handler (app terminated / background)
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print('🔕 Background message: ${message.messageId}');
  _showNotification(
    message.notification?.title,
    message.notification?.body,
  );
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize local storage
  final storage = Get.put(StorageService());
  await StorageService.initStorage();
  debugPrint('Access Token => ${storage.read(AppConstant.accessToken)}');


  // Setup Firebase Messaging
  await _setupFirebaseMessaging();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(375, 812),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        return GetMaterialApp(
          theme: ThemeData(
            fontFamily: 'Poppins',
            scaffoldBackgroundColor: Colors.black,
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
            useMaterial3: true,
          ),
          debugShowCheckedModeBanner: false,
          title: "Application",
          initialRoute: AppPages.INITIAL,
          getPages: AppPages.routes,
          builder: (context, widget) => widget ?? const SizedBox.shrink(),
        );
      },
    );
  }
}

Future<void> _setupFirebaseMessaging() async {
  try {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    // Request permissions (iOS)
    await messaging.requestPermission(alert: true, badge: true, sound: true);

    // Get FCM token
    final token = await messaging.getToken();
    if (token != null) {
      print("📲 FCM Token: $token");
      await LocalStorage.saveData(key: AppConstant.fcmToken, data: token);
    }

    // Listen for token refresh
    FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
      print("♻ Token refreshed: $newToken");
      await LocalStorage.saveData(key: AppConstant.fcmToken, data: newToken);
    });

    // Initialize local notifications
    const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosSettings = DarwinInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
    );

    final initSettings = InitializationSettings(
      android: androidSettings,
      iOS: iosSettings,
    );

    await flutterLocalNotificationsPlugin.initialize(
      initSettings,
      onDidReceiveNotificationResponse: (NotificationResponse response) async {
        if (response.payload != null) {
          print('🔗 Notification payload: ${response.payload}');
        }
      },
    );

    // Foreground messages
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('📬 Foreground: ${message.notification?.title}');
      _showNotification(
        message.notification?.title,
        message.notification?.body,
      );
    });

    // Background / terminated messages
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  } catch (e) {
    print("❌ Firebase Messaging setup failed: $e");
  }
}

// Local notification function
Future<void> _showNotification(String? title, String? body) async {
  const androidDetails = AndroidNotificationDetails(
    'default_channel_id',
    'General Notifications',
    importance: Importance.max,
    priority: Priority.high,
    playSound: true,
  );

  const iosDetails = DarwinNotificationDetails();

  const platformDetails = NotificationDetails(
    android: androidDetails,
    iOS: iosDetails,
  );

  await flutterLocalNotificationsPlugin.show(
    0,
    title ?? 'No Title',
    body ?? 'No Message',
    platformDetails,
    payload: 'notification_payload',
  );
}
